import type { Tool } from './types'

const selection: Tool[] = [
  {
    id: 'tool.select',
    name: 'Select',
    icon: 'MousePointer2',
    tooltip: 'Select objects',
    shortcut: 'v',
    description: 'Click an object to select it. Shift-click to add to selection.',
    category: 'selection',
    inputs: ['pointer position'],
    outputs: ['selection set'],
    sideEffects: ['updates selectionStore'],
    errorStates: [],
    undoBehavior: 'none',
    voiceCommandExamples: ['select the pool', 'select the deck'],
  },
  {
    id: 'tool.pan',
    name: 'Pan',
    icon: 'Hand',
    tooltip: 'Pan the canvas',
    shortcut: 'h',
    description: 'Drag to pan the canvas. Hold space to temporarily activate.',
    category: 'selection',
    inputs: ['drag delta'],
    outputs: ['updated panX/panY'],
    sideEffects: ['updates editorStore.panX/panY'],
    errorStates: [],
    undoBehavior: 'none',
    voiceCommandExamples: ['pan left', 'pan up'],
  },
  {
    id: 'tool.zoom',
    name: 'Zoom',
    icon: 'ZoomIn',
    tooltip: 'Zoom in or out',
    shortcut: null,
    description: 'Scroll or pinch to zoom. + and - keys also zoom.',
    category: 'selection',
    inputs: ['delta or absolute zoom level'],
    outputs: ['updated zoom'],
    sideEffects: ['updates editorStore.zoom'],
    errorStates: ['zoom out of range'],
    undoBehavior: 'none',
    voiceCommandExamples: ['zoom in', 'zoom to 200 percent'],
  },
  {
    id: 'tool.multi-select',
    name: 'Multi select',
    icon: 'BoxSelect',
    tooltip: 'Drag a marquee to select multiple objects',
    shortcut: null,
    description: 'Drag an empty area to draw a selection rectangle.',
    category: 'selection',
    inputs: ['marquee rect'],
    outputs: ['selection set'],
    sideEffects: ['updates selectionStore'],
    errorStates: [],
    undoBehavior: 'none',
    voiceCommandExamples: ['select all in this area'],
  },
  {
    id: 'tool.group',
    name: 'Group',
    icon: 'Group',
    tooltip: 'Group selected objects',
    shortcut: 'mod+g',
    description: 'Combine selected objects into a group.',
    category: 'selection',
    inputs: ['selection set'],
    outputs: ['group id'],
    sideEffects: ['mutates drawing object tree'],
    errorStates: ['fewer than 2 objects selected'],
    undoBehavior: 'restore previous parent ids',
    voiceCommandExamples: ['group selected'],
  },
  {
    id: 'tool.ungroup',
    name: 'Ungroup',
    icon: 'Ungroup',
    tooltip: 'Ungroup selected objects',
    shortcut: 'mod+shift+g',
    description: 'Disband a group, leaving its children selected.',
    category: 'selection',
    inputs: ['group id'],
    outputs: ['child ids'],
    sideEffects: ['mutates drawing object tree'],
    errorStates: ['selection is not a group'],
    undoBehavior: 'restore group',
    voiceCommandExamples: ['ungroup'],
  },
  {
    id: 'tool.lock',
    name: 'Lock',
    icon: 'Lock',
    tooltip: 'Lock selected objects',
    shortcut: null,
    description: 'Prevent selected objects from being moved or edited.',
    category: 'selection',
    inputs: ['selection set'],
    outputs: ['locked state'],
    sideEffects: ['mutates drawing objects'],
    errorStates: [],
    undoBehavior: 'unlock',
    voiceCommandExamples: ['lock selection'],
  },
  {
    id: 'tool.hide',
    name: 'Hide',
    icon: 'EyeOff',
    tooltip: 'Hide selected objects',
    shortcut: null,
    description: 'Toggle visibility of selected objects.',
    category: 'selection',
    inputs: ['selection set'],
    outputs: ['hidden state'],
    sideEffects: ['mutates drawing objects'],
    errorStates: [],
    undoBehavior: 'show',
    voiceCommandExamples: ['hide selection'],
  },
]

const drawing: Tool[] = [
  {
    id: 'tool.add-pool',
    name: 'Add pool',
    icon: 'Square',
    tooltip: 'Draw a rectangle pool',
    shortcut: null,
    description: 'Click and drag on the canvas to draw a rectangle pool.',
    category: 'drawing',
    inputs: ['rect bounds', 'stencil id'],
    outputs: ['drawing object id'],
    sideEffects: ['creates DrawingObject', 'recalculates measurements'],
    errorStates: ['zero-size rect'],
    undoBehavior: 'delete created object',
    voiceCommandExamples: ['add a rectangle pool 25 by 10', 'add a roman pool'],
  },
  {
    id: 'tool.add-freeform-pool',
    name: 'Add freeform pool',
    icon: 'Spline',
    tooltip: 'Draw a freeform pool',
    shortcut: null,
    description: 'Click points to define a freeform pool outline.',
    category: 'drawing',
    inputs: ['point list'],
    outputs: ['drawing object id'],
    sideEffects: ['creates DrawingObject', 'recalculates measurements'],
    errorStates: ['fewer than 3 points'],
    undoBehavior: 'delete created object',
    voiceCommandExamples: ['add a freeform pool'],
  },
  {
    id: 'tool.add-deck',
    name: 'Add deck',
    icon: 'Square',
    tooltip: 'Draw a deck',
    shortcut: null,
    description: 'Click and drag to draw a rectangular deck.',
    category: 'drawing',
    inputs: ['rect bounds', 'material id'],
    outputs: ['drawing object id'],
    sideEffects: ['creates DrawingObject', 'recalculates deck area'],
    errorStates: [],
    undoBehavior: 'delete created object',
    voiceCommandExamples: ['add a paver deck'],
  },
  {
    id: 'tool.add-lanai',
    name: 'Add lanai',
    icon: 'Home',
    tooltip: 'Draw a lanai',
    shortcut: null,
    description: 'Click and drag to draw a lanai outline.',
    category: 'drawing',
    inputs: ['rect bounds'],
    outputs: ['drawing object id'],
    sideEffects: ['creates DrawingObject', 'recalculates lanai area'],
    errorStates: [],
    undoBehavior: 'delete created object',
    voiceCommandExamples: ['add a lanai'],
  },
  {
    id: 'tool.add-spa',
    name: 'Add spa',
    icon: 'Hexagon',
    tooltip: 'Draw a spa',
    shortcut: null,
    description: 'Click to drop a spa stencil at pointer position.',
    category: 'drawing',
    inputs: ['point'],
    outputs: ['drawing object id'],
    sideEffects: ['creates DrawingObject'],
    errorStates: [],
    undoBehavior: 'delete created object',
    voiceCommandExamples: ['add a spa'],
  },
  {
    id: 'tool.add-steps',
    name: 'Add steps',
    icon: 'Steps',
    tooltip: 'Add pool steps',
    shortcut: null,
    description: 'Click on a pool edge to add steps.',
    category: 'drawing',
    inputs: ['edge anchor', 'step variant'],
    outputs: ['drawing object id'],
    sideEffects: ['creates DrawingObject child of pool'],
    errorStates: ['no pool selected'],
    undoBehavior: 'delete created object',
    voiceCommandExamples: ['add corner steps'],
  },
  {
    id: 'tool.add-bench',
    name: 'Add bench',
    icon: 'Minus',
    tooltip: 'Add a bench',
    shortcut: null,
    description: 'Click on a pool edge to add a bench.',
    category: 'drawing',
    inputs: ['edge anchor'],
    outputs: ['drawing object id'],
    sideEffects: ['creates DrawingObject child of pool'],
    errorStates: ['no pool selected'],
    undoBehavior: 'delete created object',
    voiceCommandExamples: ['add a swim out bench on the left'],
  },
  {
    id: 'tool.add-tanning-ledge',
    name: 'Add tanning ledge',
    icon: 'Sun',
    tooltip: 'Add a tanning ledge',
    shortcut: null,
    description: 'Click and drag inside a pool to add a tanning ledge.',
    category: 'drawing',
    inputs: ['rect bounds', 'parent pool id'],
    outputs: ['drawing object id'],
    sideEffects: ['creates DrawingObject child of pool'],
    errorStates: ['no pool selected'],
    undoBehavior: 'delete created object',
    voiceCommandExamples: ['add a tanning ledge'],
  },
  {
    id: 'tool.add-drain',
    name: 'Add drain',
    icon: 'Disc',
    tooltip: 'Add main drain or deco drain',
    shortcut: null,
    description: 'Click to drop a drain marker. Drag for deco drain length.',
    category: 'drawing',
    inputs: ['point or line'],
    outputs: ['drawing object id'],
    sideEffects: ['creates DrawingObject', 'recalculates deco drain LF'],
    errorStates: [],
    undoBehavior: 'delete created object',
    voiceCommandExamples: ['add a deco drain along the back'],
  },
  {
    id: 'tool.add-dimension-line',
    name: 'Add dimension line',
    icon: 'Ruler',
    tooltip: 'Add a labeled dimension line',
    shortcut: null,
    description: 'Click two points to draw a dimension line with computed length.',
    category: 'drawing',
    inputs: ['two points'],
    outputs: ['drawing object id'],
    sideEffects: ['creates DrawingObject'],
    errorStates: [],
    undoBehavior: 'delete created object',
    voiceCommandExamples: ['add a dimension line'],
  },
  {
    id: 'tool.add-label',
    name: 'Add label',
    icon: 'Type',
    tooltip: 'Add a text label',
    shortcut: null,
    description: 'Click to place a text label.',
    category: 'drawing',
    inputs: ['point', 'text'],
    outputs: ['drawing object id'],
    sideEffects: ['creates DrawingObject'],
    errorStates: ['empty text'],
    undoBehavior: 'delete created object',
    voiceCommandExamples: ['add a label that says shallow end'],
  },
  {
    id: 'tool.add-callout',
    name: 'Add callout',
    icon: 'MessageCircle',
    tooltip: 'Add a numbered callout',
    shortcut: null,
    description: 'Click to drop a numbered callout marker.',
    category: 'drawing',
    inputs: ['point'],
    outputs: ['drawing object id'],
    sideEffects: ['creates DrawingObject'],
    errorStates: [],
    undoBehavior: 'delete created object',
    voiceCommandExamples: ['add callout 3 here'],
  },
]

const transform: Tool[] = [
  {
    id: 'tool.move',
    name: 'Move',
    icon: 'Move',
    tooltip: 'Move selected objects',
    shortcut: null,
    description: 'Drag selected objects to a new position.',
    category: 'transform',
    inputs: ['delta'],
    outputs: ['new position'],
    sideEffects: ['mutates DrawingObject geometry'],
    errorStates: ['object locked'],
    undoBehavior: 'restore previous position',
    voiceCommandExamples: ['move pool right 2 feet'],
  },
  {
    id: 'tool.resize',
    name: 'Resize',
    icon: 'Scale',
    tooltip: 'Resize selected objects',
    shortcut: null,
    description: 'Drag transform handles to resize.',
    category: 'transform',
    inputs: ['handle', 'delta'],
    outputs: ['new dimensions'],
    sideEffects: ['mutates geometry', 'recalculates measurements'],
    errorStates: ['object locked', 'minimum size violated'],
    undoBehavior: 'restore previous dimensions',
    voiceCommandExamples: ['resize the pool to 30 by 14'],
  },
  {
    id: 'tool.rotate',
    name: 'Rotate',
    icon: 'RotateCw',
    tooltip: 'Rotate selected objects',
    shortcut: null,
    description: 'Drag the rotation handle to rotate.',
    category: 'transform',
    inputs: ['angle delta'],
    outputs: ['new rotation'],
    sideEffects: ['mutates geometry'],
    errorStates: ['object locked'],
    undoBehavior: 'restore previous angle',
    voiceCommandExamples: ['rotate the spa 45 degrees'],
  },
  {
    id: 'tool.flip-horizontal',
    name: 'Flip horizontal',
    icon: 'FlipHorizontal',
    tooltip: 'Mirror across vertical axis',
    shortcut: null,
    description: 'Flip selection horizontally.',
    category: 'transform',
    inputs: ['selection set'],
    outputs: ['mirrored geometry'],
    sideEffects: ['mutates geometry'],
    errorStates: [],
    undoBehavior: 'flip again',
    voiceCommandExamples: ['flip selection horizontally'],
  },
  {
    id: 'tool.flip-vertical',
    name: 'Flip vertical',
    icon: 'FlipVertical',
    tooltip: 'Mirror across horizontal axis',
    shortcut: null,
    description: 'Flip selection vertically.',
    category: 'transform',
    inputs: ['selection set'],
    outputs: ['mirrored geometry'],
    sideEffects: ['mutates geometry'],
    errorStates: [],
    undoBehavior: 'flip again',
    voiceCommandExamples: ['flip selection vertically'],
  },
  {
    id: 'tool.align',
    name: 'Align',
    icon: 'AlignStartHorizontal',
    tooltip: 'Align selected objects',
    shortcut: null,
    description: 'Align by left, right, top, bottom, center horizontal, or center vertical.',
    category: 'transform',
    inputs: ['alignment mode'],
    outputs: ['updated positions'],
    sideEffects: ['mutates geometry'],
    errorStates: ['fewer than 2 objects'],
    undoBehavior: 'restore previous positions',
    voiceCommandExamples: ['align left'],
  },
  {
    id: 'tool.distribute',
    name: 'Distribute',
    icon: 'Columns3',
    tooltip: 'Distribute selected objects evenly',
    shortcut: null,
    description: 'Distribute spacing horizontally or vertically.',
    category: 'transform',
    inputs: ['distribution axis'],
    outputs: ['updated positions'],
    sideEffects: ['mutates geometry'],
    errorStates: ['fewer than 3 objects'],
    undoBehavior: 'restore previous positions',
    voiceCommandExamples: ['distribute horizontally'],
  },
  {
    id: 'tool.bring-forward',
    name: 'Bring forward',
    icon: 'ChevronUp',
    tooltip: 'Bring selection one step forward',
    shortcut: null,
    description: 'Increment z-index of selection by one.',
    category: 'transform',
    inputs: ['selection set'],
    outputs: ['updated z-index'],
    sideEffects: ['mutates DrawingObject zIndex'],
    errorStates: [],
    undoBehavior: 'send back one step',
    voiceCommandExamples: ['bring forward'],
  },
  {
    id: 'tool.send-backward',
    name: 'Send backward',
    icon: 'ChevronDown',
    tooltip: 'Send selection one step backward',
    shortcut: null,
    description: 'Decrement z-index of selection by one.',
    category: 'transform',
    inputs: ['selection set'],
    outputs: ['updated z-index'],
    sideEffects: ['mutates DrawingObject zIndex'],
    errorStates: [],
    undoBehavior: 'bring forward one step',
    voiceCommandExamples: ['send backward'],
  },
]

const measurement: Tool[] = [
  {
    id: 'tool.measure-area',
    name: 'Measure area',
    icon: 'SquareDashed',
    tooltip: 'Measure surface area',
    shortcut: null,
    description: 'Display surface area of selected shape.',
    category: 'measurement',
    inputs: ['selection set'],
    outputs: ['area in sqft'],
    sideEffects: [],
    errorStates: ['no shape selected'],
    undoBehavior: 'none',
    voiceCommandExamples: ['what is the area of the pool'],
  },
  {
    id: 'tool.measure-perimeter',
    name: 'Measure perimeter',
    icon: 'Frame',
    tooltip: 'Measure perimeter',
    shortcut: null,
    description: 'Display perimeter of selected shape.',
    category: 'measurement',
    inputs: ['selection set'],
    outputs: ['perimeter in lf'],
    sideEffects: [],
    errorStates: ['no shape selected'],
    undoBehavior: 'none',
    voiceCommandExamples: ['what is the perimeter'],
  },
  {
    id: 'tool.measure-length',
    name: 'Measure length',
    icon: 'MoveHorizontal',
    tooltip: 'Measure length',
    shortcut: null,
    description: 'Display length of selected shape.',
    category: 'measurement',
    inputs: ['selection set'],
    outputs: ['length in ft'],
    sideEffects: [],
    errorStates: ['no shape selected'],
    undoBehavior: 'none',
    voiceCommandExamples: ['how long is the pool'],
  },
  {
    id: 'tool.measure-width',
    name: 'Measure width',
    icon: 'MoveVertical',
    tooltip: 'Measure width',
    shortcut: null,
    description: 'Display width of selected shape.',
    category: 'measurement',
    inputs: ['selection set'],
    outputs: ['width in ft'],
    sideEffects: [],
    errorStates: ['no shape selected'],
    undoBehavior: 'none',
    voiceCommandExamples: ['how wide is the pool'],
  },
  {
    id: 'tool.measure-angle',
    name: 'Measure angle',
    icon: 'Triangle',
    tooltip: 'Measure angle',
    shortcut: null,
    description: 'Display rotation angle of selected shape.',
    category: 'measurement',
    inputs: ['selection set'],
    outputs: ['angle in degrees'],
    sideEffects: [],
    errorStates: ['no shape selected'],
    undoBehavior: 'none',
    voiceCommandExamples: ['what angle is the spa rotated'],
  },
  {
    id: 'tool.set-scale',
    name: 'Set scale',
    icon: 'Compass',
    tooltip: 'Set canvas scale',
    shortcut: null,
    description: 'Calibrate the canvas scale using a known distance.',
    category: 'measurement',
    inputs: ['two points', 'real-world length'],
    outputs: ['updated scale'],
    sideEffects: ['updates Drawing.scale'],
    errorStates: ['zero-length input'],
    undoBehavior: 'restore previous scale',
    voiceCommandExamples: ['set scale: this line is 20 feet'],
  },
  {
    id: 'tool.resize-by-target-area',
    name: 'Resize by target area',
    icon: 'Maximize2',
    tooltip: 'Resize pool to a target square footage',
    shortcut: null,
    description: 'Scale pool proportionally to match a target surface area.',
    category: 'measurement',
    inputs: ['target sqft', 'selected pool'],
    outputs: ['new dimensions'],
    sideEffects: ['mutates geometry', 'recalculates measurements'],
    errorStates: ['no pool selected', 'unreachable target'],
    undoBehavior: 'restore previous dimensions',
    voiceCommandExamples: ['resize the pool to 238 square feet'],
  },
  {
    id: 'tool.show-radius',
    name: 'Show radius',
    icon: 'CircleDot',
    tooltip: 'Show curve radius labels',
    shortcut: null,
    description: 'Display radius labels on freeform shape curves.',
    category: 'measurement',
    inputs: ['selection set'],
    outputs: ['radius labels'],
    sideEffects: ['toggles overlay state'],
    errorStates: ['shape has no curves'],
    undoBehavior: 'hide labels',
    voiceCommandExamples: ['show radius'],
  },
]

const pricing: Tool[] = [
  {
    id: 'tool.open-quote',
    name: 'Open quote',
    icon: 'FileText',
    tooltip: 'Open the live quote panel',
    shortcut: null,
    description: 'Slide open the quote panel showing all line items.',
    category: 'pricing',
    inputs: [],
    outputs: ['quote panel visible'],
    sideEffects: ['toggles editorStore.quotePanelOpen'],
    errorStates: [],
    undoBehavior: 'none',
    voiceCommandExamples: ['show me the quote', 'open the quote'],
  },
  {
    id: 'tool.add-line-item',
    name: 'Add line item',
    icon: 'Plus',
    tooltip: 'Add a manual line item to the quote',
    shortcut: null,
    description: 'Add a line item from the price book or a custom one.',
    category: 'pricing',
    inputs: ['price book item id', 'quantity'],
    outputs: ['quote line item id'],
    sideEffects: ['mutates Quote'],
    errorStates: ['item not found'],
    undoBehavior: 'remove line item',
    voiceCommandExamples: ['add a Pentair salt system'],
  },
  {
    id: 'tool.remove-line-item',
    name: 'Remove line item',
    icon: 'Minus',
    tooltip: 'Remove a line item from the quote',
    shortcut: null,
    description: 'Delete the selected quote line item.',
    category: 'pricing',
    inputs: ['quote line item id'],
    outputs: [],
    sideEffects: ['mutates Quote'],
    errorStates: ['item is required'],
    undoBehavior: 'restore line item',
    voiceCommandExamples: ['remove the heater line item'],
  },
  {
    id: 'tool.select-equipment',
    name: 'Select equipment',
    icon: 'Wrench',
    tooltip: 'Choose equipment package',
    shortcut: null,
    description: 'Select pump, filter, sanitization, heater, lighting.',
    category: 'pricing',
    inputs: ['equipment selections'],
    outputs: ['updated quote line items'],
    sideEffects: ['mutates project poolFields', 'recalculates quote'],
    errorStates: ['invalid combo'],
    undoBehavior: 'restore previous selections',
    voiceCommandExamples: ['select the premium equipment package'],
  },
  {
    id: 'tool.select-finish',
    name: 'Select finish',
    icon: 'Palette',
    tooltip: 'Choose interior finish',
    shortcut: null,
    description: 'Select pool interior finish.',
    category: 'pricing',
    inputs: ['finish id'],
    outputs: ['updated quote line item'],
    sideEffects: ['mutates project poolFields', 'recalculates finish line'],
    errorStates: [],
    undoBehavior: 'restore previous finish',
    voiceCommandExamples: ['select pebble tec finish'],
  },
  {
    id: 'tool.select-deck-material',
    name: 'Select deck material',
    icon: 'LayoutGrid',
    tooltip: 'Choose deck material',
    shortcut: null,
    description: 'Pick concrete, pavers, or another deck material.',
    category: 'pricing',
    inputs: ['material id', 'deck object id'],
    outputs: ['updated quote line items'],
    sideEffects: ['mutates DrawingObject material', 'recalculates deck line'],
    errorStates: [],
    undoBehavior: 'restore previous material',
    voiceCommandExamples: ['change the deck to pavers'],
  },
  {
    id: 'tool.select-heater',
    name: 'Select heater',
    icon: 'Flame',
    tooltip: 'Choose heater',
    shortcut: null,
    description: 'Pick gas heater, electric heat pump, or none.',
    category: 'pricing',
    inputs: ['heater id'],
    outputs: ['updated quote line item'],
    sideEffects: ['mutates project poolFields', 'recalculates heater line'],
    errorStates: ['heater requires gas line note'],
    undoBehavior: 'restore previous heater',
    voiceCommandExamples: ['add a gas heater'],
  },
  {
    id: 'tool.apply-discount',
    name: 'Apply discount',
    icon: 'BadgePercent',
    tooltip: 'Apply a discount',
    shortcut: null,
    description: 'Apply a percentage or fixed-amount discount.',
    category: 'pricing',
    inputs: ['discount kind', 'amount'],
    outputs: ['updated total'],
    sideEffects: ['mutates Quote'],
    errorStates: ['discount exceeds subtotal'],
    undoBehavior: 'remove discount',
    voiceCommandExamples: ['apply a 5 percent discount'],
  },
  {
    id: 'tool.recalculate-quote',
    name: 'Recalculate quote',
    icon: 'RefreshCw',
    tooltip: 'Recalculate all line items',
    shortcut: null,
    description: 'Re-evaluate every formula-driven line item.',
    category: 'pricing',
    inputs: [],
    outputs: ['updated Quote'],
    sideEffects: ['mutates Quote'],
    errorStates: ['price book missing'],
    undoBehavior: 'none',
    voiceCommandExamples: ['recalculate the quote'],
  },
]

const exportTools: Tool[] = [
  {
    id: 'tool.export-proposal',
    name: 'Export proposal',
    icon: 'FileDown',
    tooltip: 'Export customer proposal PDF',
    shortcut: null,
    description: 'Generate the customer proposal PDF.',
    category: 'export',
    inputs: ['project id'],
    outputs: ['Export row', 'PDF url'],
    sideEffects: ['runs validation', 'persists Export row'],
    errorStates: ['validation blocking errors'],
    undoBehavior: 'none (export is durable)',
    voiceCommandExamples: ['export the customer proposal'],
  },
  {
    id: 'tool.export-construction-packet',
    name: 'Export construction packet',
    icon: 'FileBox',
    tooltip: 'Export construction packet PDF',
    shortcut: null,
    description: 'Generate the construction packet PDF.',
    category: 'export',
    inputs: ['project id'],
    outputs: ['Export row', 'PDF url'],
    sideEffects: ['runs validation', 'persists Export row'],
    errorStates: ['validation blocking errors'],
    undoBehavior: 'none (export is durable)',
    voiceCommandExamples: ['export the construction packet'],
  },
  {
    id: 'tool.export-image',
    name: 'Export image',
    icon: 'Image',
    tooltip: 'Export drawing as PNG',
    shortcut: null,
    description: 'Render the canvas to a PNG image.',
    category: 'export',
    inputs: ['project id', 'resolution'],
    outputs: ['Export row', 'image url'],
    sideEffects: ['persists Export row'],
    errorStates: [],
    undoBehavior: 'none',
    voiceCommandExamples: ['export the drawing as an image'],
  },
  {
    id: 'tool.print',
    name: 'Print',
    icon: 'Printer',
    tooltip: 'Print the current view',
    shortcut: null,
    description: 'Open the print dialog.',
    category: 'export',
    inputs: [],
    outputs: [],
    sideEffects: ['triggers browser print'],
    errorStates: [],
    undoBehavior: 'none',
    voiceCommandExamples: ['print the layout'],
  },
  {
    id: 'tool.duplicate-project',
    name: 'Duplicate project',
    icon: 'Copy',
    tooltip: 'Duplicate this project',
    shortcut: null,
    description: 'Create a copy of the current project.',
    category: 'export',
    inputs: ['project id'],
    outputs: ['new project id'],
    sideEffects: ['inserts Project row', 'clones Drawing'],
    errorStates: [],
    undoBehavior: 'delete duplicated project',
    voiceCommandExamples: ['duplicate this project'],
  },
]

export const TOOLS: Tool[] = [
  ...selection,
  ...drawing,
  ...transform,
  ...measurement,
  ...pricing,
  ...exportTools,
]

export function toolsByCategory(): Record<Tool['category'], Tool[]> {
  return {
    selection,
    drawing,
    transform,
    measurement,
    pricing,
    export: exportTools,
  }
}

export function getTool(id: string): Tool | undefined {
  return TOOLS.find((t) => t.id === id)
}

export type { Tool } from './types'
