// BlobStore: the only sanctioned path for image bytes. Nothing binary goes in
// Postgres and no data URL goes in `Drawing.rootJson`; rows carry a
// `storageKey` and the store resolves it.
//
// The interface is deliberately driver-shaped so a GCS driver drops in behind
// `getBlobStore()` without a single caller changing.

import type { Readable } from 'node:stream'

/**
 * Opaque, driver-agnostic object address. Sharded by sha256 prefix so no
 * directory grows unbounded on the local-disk driver and so the key is a
 * valid GCS object name unchanged:
 *
 *   `ab/cd/abcd…ef.png`
 *
 * Keys are generated by the store, never taken from user input. The pattern is
 * enforced on every read so a hostile key cannot escape the blob root.
 */
export const STORAGE_KEY_PATTERN = /^[0-9a-f]{2}\/[0-9a-f]{2}\/[0-9a-f]{64}(\.[a-z0-9]{1,8})?$/

export function isStorageKey(value: string): boolean {
  return STORAGE_KEY_PATTERN.test(value)
}

export interface PutBlobInput {
  data: Buffer
  mimeType: string
}

export interface PutBlobResult {
  storageKey: string
  sha256: string
  bytes: number
  mimeType: string
  /** False when an object with the same content already existed. */
  created: boolean
}

export interface BlobStore {
  put(input: PutBlobInput): Promise<PutBlobResult>
  get(storageKey: string): Promise<Buffer>
  getStream(storageKey: string): Promise<Readable>
  delete(storageKey: string): Promise<void>
  exists(storageKey: string): Promise<boolean>
}

export class BlobNotFoundError extends Error {
  constructor(storageKey: string) {
    super(`Blob not found: ${storageKey}`)
    this.name = 'BlobNotFoundError'
  }
}

export class InvalidStorageKeyError extends Error {
  constructor(storageKey: string) {
    super(`Invalid storage key: ${storageKey}`)
    this.name = 'InvalidStorageKeyError'
  }
}

/**
 * Extensions we are willing to write. The value is decoration only: reads
 * address the key, never the extension, and an unknown type simply gets none.
 */
const MIME_EXTENSIONS: Record<string, string> = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/jpg': 'jpg',
  'image/webp': 'webp',
  'image/gif': 'gif',
  'image/heic': 'heic',
  'image/heif': 'heif',
  'image/avif': 'avif',
  'image/tiff': 'tiff',
  'application/pdf': 'pdf',
}

export function extensionForMimeType(mimeType: string): string | null {
  const normalized = mimeType.toLowerCase().split(';')[0]?.trim() ?? ''
  return MIME_EXTENSIONS[normalized] ?? null
}

/** `ab/cd/<sha256>.<ext>`. Pure, so both drivers derive the same key. */
export function storageKeyFor(sha256: string, mimeType: string): string {
  const hex = sha256.toLowerCase()
  if (!/^[0-9a-f]{64}$/.test(hex)) {
    throw new Error(`storageKeyFor expects a hex sha256, got: ${sha256}`)
  }
  const ext = extensionForMimeType(mimeType)
  const base = `${hex.slice(0, 2)}/${hex.slice(2, 4)}/${hex}`
  return ext ? `${base}.${ext}` : base
}
