// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/docs/commands" | "/docs/tools" | "/intake/[token]" | "/login" | "/projects/[id]" | "/projects/[id]/construction" | "/projects/[id]/editor" | "/projects/[id]/import" | "/projects/[id]/proposal" | "/projects/[id]/screen-enclosure-quote" | "/projects/[id]/site-plan" | "/register" | "/settings/company" | "/settings/intake" | "/settings/price-book" | "/settings/price-book/import" | "/settings/voice" | "/share/[token]"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/capture/heightfield" | "/api/commands" | "/api/exports/[id]" | "/api/imports/blob/[key]" | "/api/imports/upload" | "/api/intake/[token]" | "/api/monitoring/report" | "/api/voice/surfaces" | "/api/voice/ticket" | "/share/[token]/document"
type PageRoutes = never
type LayoutRoutes = "/" | "/docs"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/capture/heightfield": {}
  "/api/commands": {}
  "/api/exports/[id]": { "id": string; }
  "/api/imports/blob/[key]": { "key": string; }
  "/api/imports/upload": {}
  "/api/intake/[token]": { "token": string; }
  "/api/monitoring/report": {}
  "/api/voice/surfaces": {}
  "/api/voice/ticket": {}
  "/dashboard": {}
  "/docs": {}
  "/docs/commands": {}
  "/docs/tools": {}
  "/intake/[token]": { "token": string; }
  "/login": {}
  "/projects/[id]": { "id": string; }
  "/projects/[id]/construction": { "id": string; }
  "/projects/[id]/editor": { "id": string; }
  "/projects/[id]/import": { "id": string; }
  "/projects/[id]/proposal": { "id": string; }
  "/projects/[id]/screen-enclosure-quote": { "id": string; }
  "/projects/[id]/site-plan": { "id": string; }
  "/register": {}
  "/settings/company": {}
  "/settings/intake": {}
  "/settings/price-book": {}
  "/settings/price-book/import": {}
  "/settings/voice": {}
  "/share/[token]": { "token": string; }
  "/share/[token]/document": { "token": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/docs": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
