// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/docs/commands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/commands">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/docs/commands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/docs/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/tools">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/docs/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[id]/construction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]/construction">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[id]/construction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[id]/editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]/editor">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[id]/editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[id]/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]/import">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[id]/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[id]/proposal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]/proposal">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[id]/proposal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[id]/screen-enclosure-quote/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]/screen-enclosure-quote">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[id]/screen-enclosure-quote/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[id]/site-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]/site-plan">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[id]/site-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/company">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/intake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/intake">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/intake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/price-book/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/price-book/import">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/price-book/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/price-book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/price-book">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/price-book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/voice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/voice">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/voice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/intake/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intake/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/intake/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/share/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/share/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/capture/heightfield/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/capture/heightfield">> = Specific
  const handler = {} as typeof import("../../src/app/api/capture/heightfield/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/commands/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commands">> = Specific
  const handler = {} as typeof import("../../src/app/api/commands/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/exports/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exports/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/exports/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/imports/blob/[key]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imports/blob/[key]">> = Specific
  const handler = {} as typeof import("../../src/app/api/imports/blob/[key]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/imports/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imports/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/imports/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/intake/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intake/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/api/intake/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/voice/surfaces/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/surfaces">> = Specific
  const handler = {} as typeof import("../../src/app/api/voice/surfaces/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/voice/ticket/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/ticket">> = Specific
  const handler = {} as typeof import("../../src/app/api/voice/ticket/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/share/[token]/document/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/share/[token]/document">> = Specific
  const handler = {} as typeof import("../../src/app/share/[token]/document/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(app)/docs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/docs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
