import {
  StencilCategory,
  MeasurementBehavior,
  PricingBehavior,
  ExportVisibility,
  EditableProperty,
  ShapeKind,
  type Stencil,
} from './types'

const POOL_WATER_FILL = '#5BA8D6'
const POOL_STROKE = '#2C5F84'
const SPA_FILL = '#7BC2DD'
const CONCRETE_FILL = '#D6D2C7'
const PAVER_FILL = '#B69B7C'
const GRASS_FILL = '#7FB069'
const LANAI_FILL = '#E5DCC5'
const SCREEN_FILL = '#9CA3AF'
const COPING_FILL = '#C4B6A0'
const FEATURE_FILL = '#FEE2A8'
const FEATURE_STROKE = '#A87E2A'
const SYMBOL_FILL = '#FFFFFF'
const SYMBOL_STROKE = '#1F2937'
const FIRE_FILL = '#E25822'
const WATER_FEATURE_FILL = '#7FB7D6'

const inches = (width: number, height: number): Stencil['defaultDimensions'] => ({ width, height, unit: 'in' })
const feet = (width: number, height: number): Stencil['defaultDimensions'] => ({ width, height, unit: 'ft' })

// Pool shapes — dimensions in inches (1 ft = 12 in)
const poolShapes: Stencil[] = [
  {
    id: 'pool.rectangle',
    name: 'Standard rectangle',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(360, 168),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.POOL_AREA_PERIMETER_GALLONS,
    pricingBehavior: PricingBehavior.POOL_BASE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.DEPTH_SHALLOW, EditableProperty.DEPTH_DEEP, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.RECTANGLE_POOL,
  },
  {
    id: 'pool.round-corners',
    name: 'Round corners',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(360, 168),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.POOL_AREA_PERIMETER_GALLONS,
    pricingBehavior: PricingBehavior.POOL_BASE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.RADIUS, EditableProperty.DEPTH_SHALLOW, EditableProperty.DEPTH_DEEP, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.grecian',
    name: 'Grecian',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(396, 192),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.POOL_AREA_PERIMETER_GALLONS,
    pricingBehavior: PricingBehavior.POOL_BASE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.DEPTH_SHALLOW, EditableProperty.DEPTH_DEEP, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.roman',
    name: 'Roman',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(396, 192),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.POOL_AREA_PERIMETER_GALLONS,
    pricingBehavior: PricingBehavior.POOL_BASE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.DEPTH_SHALLOW, EditableProperty.DEPTH_DEEP, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.roman-two-master',
    name: 'Roman two master',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(420, 204),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.POOL_AREA_PERIMETER_GALLONS,
    pricingBehavior: PricingBehavior.POOL_BASE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.DEPTH_SHALLOW, EditableProperty.DEPTH_DEEP, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.roman-two-point-one-master',
    name: 'Roman two point one master',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(432, 216),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.POOL_AREA_PERIMETER_GALLONS,
    pricingBehavior: PricingBehavior.POOL_BASE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.DEPTH_SHALLOW, EditableProperty.DEPTH_DEEP, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.freeform-kidney',
    name: 'Freeform kidney',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(432, 240),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.POOL_AREA_PERIMETER_GALLONS,
    pricingBehavior: PricingBehavior.POOL_BASE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.DEPTH_SHALLOW, EditableProperty.DEPTH_DEEP, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.standard-steps',
    name: 'Standard steps',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(96, 36),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_FIXED,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.COUNT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.one-step',
    name: 'One step',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(96, 12),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_FIXED,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.step-sets',
    name: 'Step sets',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(96, 48),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_FIXED,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.COUNT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.corner-steps',
    name: 'Corner steps',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(60, 60),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_FIXED,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.square-steps',
    name: 'Square steps',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(72, 72),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_FIXED,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.spa',
    name: 'Spa',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(96, 96),
    defaultFill: SPA_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.SPA_AREA_PERIMETER_GALLONS,
    pricingBehavior: PricingBehavior.SPA_BASE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.DEPTH_SHALLOW, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.SPA,
  },
  {
    id: 'pool.rectangle-pool-and-spa',
    name: 'Rectangle pool and spa',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(456, 192),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.POOL_AREA_PERIMETER_GALLONS,
    pricingBehavior: PricingBehavior.POOL_BASE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.DEPTH_SHALLOW, EditableProperty.DEPTH_DEEP, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.grecian-pool-and-spa',
    name: 'Grecian pool and spa',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(480, 204),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.POOL_AREA_PERIMETER_GALLONS,
    pricingBehavior: PricingBehavior.POOL_BASE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.DEPTH_SHALLOW, EditableProperty.DEPTH_DEEP, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.roman-pool-and-spa',
    name: 'Roman pool and spa',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(480, 204),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.POOL_AREA_PERIMETER_GALLONS,
    pricingBehavior: PricingBehavior.POOL_BASE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.DEPTH_SHALLOW, EditableProperty.DEPTH_DEEP, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'pool.freeform-pool-and-spa',
    name: 'Freeform pool and spa',
    category: StencilCategory.POOL_SHAPE,
    defaultDimensions: inches(516, 252),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.POOL_AREA_PERIMETER_GALLONS,
    pricingBehavior: PricingBehavior.POOL_BASE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.DEPTH_SHALLOW, EditableProperty.DEPTH_DEEP, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
]

const interiorFeatures: Stencil[] = [
  {
    id: 'feature.swim-out-bench',
    name: 'Swim out bench',
    category: StencilCategory.INTERIOR_FEATURE,
    defaultDimensions: inches(48, 18),
    defaultFill: SPA_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.BENCH_LINEAR_FEET,
    pricingBehavior: PricingBehavior.BENCH_PER_LF,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'feature.bench',
    name: 'Bench',
    category: StencilCategory.INTERIOR_FEATURE,
    defaultDimensions: inches(60, 18),
    defaultFill: SPA_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.BENCH_LINEAR_FEET,
    pricingBehavior: PricingBehavior.BENCH_PER_LF,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.BENCH,
  },
  {
    id: 'feature.sun-shelf',
    name: 'Sun shelf',
    category: StencilCategory.INTERIOR_FEATURE,
    defaultDimensions: inches(96, 60),
    defaultFill: SPA_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.SHELF_AREA,
    pricingBehavior: PricingBehavior.FEATURE_FIXED,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.SUN_SHELF,
  },
  {
    id: 'feature.tanning-ledge',
    name: 'Tanning ledge',
    category: StencilCategory.INTERIOR_FEATURE,
    defaultDimensions: inches(120, 72),
    defaultFill: SPA_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.SHELF_AREA,
    pricingBehavior: PricingBehavior.FEATURE_FIXED,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'feature.bubblers',
    name: 'Bubblers',
    category: StencilCategory.INTERIOR_FEATURE,
    defaultDimensions: inches(6, 6),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_PER_UNIT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.COUNT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'feature.umbrella-hole',
    name: 'Umbrella hole',
    category: StencilCategory.INTERIOR_FEATURE,
    defaultDimensions: inches(4, 4),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_PER_UNIT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.COUNT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'feature.deck-jets',
    name: 'Deck jets',
    category: StencilCategory.INTERIOR_FEATURE,
    defaultDimensions: inches(6, 6),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_PER_UNIT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.COUNT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'feature.deep-end-marker',
    name: 'Deep end marker',
    category: StencilCategory.INTERIOR_FEATURE,
    defaultDimensions: inches(8, 8),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.POINT_MARKER,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LABEL, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'feature.shallow-end-marker',
    name: 'Shallow end marker',
    category: StencilCategory.INTERIOR_FEATURE,
    defaultDimensions: inches(8, 8),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.POINT_MARKER,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LABEL, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'feature.main-drain',
    name: 'Main drain',
    category: StencilCategory.INTERIOR_FEATURE,
    defaultDimensions: inches(8, 8),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_PER_UNIT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.COUNT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'feature.light',
    name: 'Light',
    category: StencilCategory.INTERIOR_FEATURE,
    defaultDimensions: inches(6, 6),
    defaultFill: '#FFE066',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_PER_UNIT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.COUNT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'feature.return',
    name: 'Return',
    category: StencilCategory.INTERIOR_FEATURE,
    defaultDimensions: inches(4, 4),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_PER_UNIT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.COUNT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
]

const deckHouse: Stencil[] = [
  {
    id: 'deck.concrete',
    name: 'Concrete deck',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(40, 24),
    defaultFill: CONCRETE_FILL,
    defaultStroke: '#8A8377',
    measurementBehavior: MeasurementBehavior.DECK_AREA,
    pricingBehavior: PricingBehavior.DECK_PER_SQFT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.CONCRETE_DECK,
  },
  {
    id: 'deck.paver',
    name: 'Paver deck',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(40, 24),
    defaultFill: PAVER_FILL,
    defaultStroke: '#7A6650',
    measurementBehavior: MeasurementBehavior.DECK_AREA,
    pricingBehavior: PricingBehavior.DECK_PER_SQFT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.PAVER_DECK,
  },
  {
    id: 'deck.grass-area',
    name: 'Grass area',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(20, 20),
    defaultFill: GRASS_FILL,
    defaultStroke: '#4F7340',
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION, EditableProperty.FILL],
    shapeKind: ShapeKind.GRASS_AREA,
  },
  {
    id: 'deck.lanai',
    name: 'Lanai',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(20, 16),
    defaultFill: LANAI_FILL,
    defaultStroke: '#A89D80',
    measurementBehavior: MeasurementBehavior.LANAI_AREA,
    pricingBehavior: PricingBehavior.LANAI_PER_SQFT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'deck.covered-lanai',
    name: 'Covered lanai',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(20, 16),
    defaultFill: LANAI_FILL,
    defaultStroke: '#A89D80',
    measurementBehavior: MeasurementBehavior.LANAI_AREA,
    pricingBehavior: PricingBehavior.LANAI_PER_SQFT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'deck.pillar',
    name: 'Pillar',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: inches(12, 12),
    defaultFill: '#A8A29E',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_PER_UNIT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.COUNT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'deck.corner-pillar',
    name: 'Corner pillar',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: inches(14, 14),
    defaultFill: '#A8A29E',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_PER_UNIT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.COUNT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'deck.wall',
    name: 'Wall',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(10, 1),
    defaultFill: '#9CA3AF',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.WALL_LINEAR_FEET,
    pricingBehavior: PricingBehavior.WALL_PER_LF,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LENGTH, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'deck.raised-deck',
    name: 'Raised deck',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(16, 12),
    defaultFill: PAVER_FILL,
    defaultStroke: '#7A6650',
    measurementBehavior: MeasurementBehavior.DECK_AREA,
    pricingBehavior: PricingBehavior.DECK_PER_SQFT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'deck.waterfall-wall',
    name: 'Waterfall wall',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(8, 1),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.WALL_LINEAR_FEET,
    pricingBehavior: PricingBehavior.WALL_PER_LF,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LENGTH, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'deck.step-down',
    name: 'Step down',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(4, 1),
    defaultFill: CONCRETE_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_PER_UNIT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'deck.drain-line',
    name: 'Drain line',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(20, 1),
    defaultFill: 'transparent',
    defaultStroke: '#1F2937',
    measurementBehavior: MeasurementBehavior.DECO_DRAIN_LINEAR_FEET,
    pricingBehavior: PricingBehavior.DECO_DRAIN_PER_LF,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LENGTH, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'deck.deco-drain',
    name: 'Deco drain',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(20, 1),
    defaultFill: 'transparent',
    defaultStroke: '#1F2937',
    measurementBehavior: MeasurementBehavior.DECO_DRAIN_LINEAR_FEET,
    pricingBehavior: PricingBehavior.DECO_DRAIN_PER_LF,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LENGTH, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'deck.coping-strip',
    name: 'Coping strip',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(20, 1),
    defaultFill: COPING_FILL,
    defaultStroke: '#8A7A5A',
    measurementBehavior: MeasurementBehavior.COPING_LINEAR_FEET,
    pricingBehavior: PricingBehavior.COPING_PER_LF,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LENGTH, EditableProperty.ROTATION, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'deck.fence',
    name: 'Fence',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(20, 1),
    defaultFill: '#6B7280',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.FENCE_LINEAR_FEET,
    pricingBehavior: PricingBehavior.FENCE_PER_LF,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LENGTH, EditableProperty.ROTATION, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'deck.screen-cage',
    name: 'Screen cage',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: feet(40, 24),
    defaultFill: SCREEN_FILL,
    defaultStroke: '#4B5563',
    measurementBehavior: MeasurementBehavior.SCREEN_AREA,
    pricingBehavior: PricingBehavior.SCREEN_PER_SQFT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'deck.access-arrow',
    name: 'Access arrow',
    category: StencilCategory.DECK_HOUSE,
    defaultDimensions: inches(48, 12),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.ROTATION, EditableProperty.LABEL],
    shapeKind: ShapeKind.STENCIL,
  },
]

const constructionSymbols: Stencil[] = [
  {
    id: 'symbol.equipment-pad',
    name: 'Equipment pad',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: feet(8, 6),
    defaultFill: CONCRETE_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_FIXED,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION, EditableProperty.NOTE],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.access-arrow',
    name: 'Access arrow',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: inches(48, 12),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.ROTATION, EditableProperty.LABEL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.construction-notes',
    name: 'Construction notes block',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: inches(192, 96),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.NOTE],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.wall-detail',
    name: 'Wall detail',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: inches(96, 96),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.NOTE],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.approval-block',
    name: 'Approval block',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: inches(192, 72),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.NOTE],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.color-selection-box',
    name: 'Color selection box',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: inches(144, 96),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.NOTE],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.upgrade-option-box',
    name: 'Upgrade option box',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: inches(144, 96),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.NOTE],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.gas-line-disclaimer',
    name: 'Gas line disclaimer',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: inches(144, 48),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.NOTE],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.power-line-disclaimer',
    name: 'Power line disclaimer',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: inches(144, 48),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.NOTE],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.job-specification-block',
    name: 'Job specification block',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: inches(192, 96),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.NOTE],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.total-pricing-block',
    name: 'Total pricing block',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: inches(144, 60),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CUSTOMER,
    affectsQuote: false,
    onConstructionSheet: false,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.NOTE],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.check-mark',
    name: 'Check mark',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: inches(12, 12),
    defaultFill: 'transparent',
    defaultStroke: '#22C55E',
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.numbered-callout',
    name: 'Numbered callout',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: inches(18, 18),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LABEL, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.dimension-line',
    name: 'Dimension line',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: feet(10, 1),
    defaultFill: 'transparent',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.DIMENSION_LINE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LENGTH, EditableProperty.ROTATION, EditableProperty.LABEL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.center-line',
    name: 'Center line',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: feet(10, 1),
    defaultFill: 'transparent',
    defaultStroke: '#6B7280',
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LENGTH, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.property-line',
    name: 'Property line',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: feet(40, 1),
    defaultFill: 'transparent',
    defaultStroke: '#1F2937',
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LENGTH, EditableProperty.ROTATION, EditableProperty.LABEL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'symbol.setback-line',
    name: 'Setback line',
    category: StencilCategory.CONSTRUCTION_SYMBOL,
    defaultDimensions: feet(20, 1),
    defaultFill: 'transparent',
    defaultStroke: '#9CA3AF',
    measurementBehavior: MeasurementBehavior.NONE,
    pricingBehavior: PricingBehavior.NONE,
    exportVisibility: ExportVisibility.CONSTRUCTION,
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LENGTH, EditableProperty.ROTATION, EditableProperty.LABEL],
    shapeKind: ShapeKind.STENCIL,
  },
]

const waterOutdoor: Stencil[] = [
  {
    id: 'water.water-bowl',
    name: 'Water bowl',
    category: StencilCategory.WATER_OUTDOOR,
    defaultDimensions: inches(24, 24),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_PER_UNIT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.COUNT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'water.fire-bowl',
    name: 'Fire bowl',
    category: StencilCategory.WATER_OUTDOOR,
    defaultDimensions: inches(24, 24),
    defaultFill: FIRE_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_PER_UNIT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.COUNT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'water.waterfall',
    name: 'Waterfall',
    category: StencilCategory.WATER_OUTDOOR,
    defaultDimensions: inches(60, 24),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_FIXED,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'water.raised-wall',
    name: 'Raised wall',
    category: StencilCategory.WATER_OUTDOOR,
    defaultDimensions: feet(8, 1),
    defaultFill: '#A8A29E',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.WALL_LINEAR_FEET,
    pricingBehavior: PricingBehavior.WALL_PER_LF,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.LENGTH, EditableProperty.ROTATION, EditableProperty.FILL, EditableProperty.MATERIAL],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'water.spillway',
    name: 'Spillway',
    category: StencilCategory.WATER_OUTDOOR,
    defaultDimensions: inches(36, 12),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_FIXED,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'water.deck-jet',
    name: 'Deck jet',
    category: StencilCategory.WATER_OUTDOOR,
    defaultDimensions: inches(6, 6),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_PER_UNIT,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.COUNT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'water.spa-spillover',
    name: 'Spa spillover',
    category: StencilCategory.WATER_OUTDOOR,
    defaultDimensions: inches(36, 12),
    defaultFill: SPA_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_FIXED,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'water.fire-pit',
    name: 'Fire pit',
    category: StencilCategory.WATER_OUTDOOR,
    defaultDimensions: inches(48, 48),
    defaultFill: FIRE_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_FIXED,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION],
    shapeKind: ShapeKind.STENCIL,
  },
  {
    id: 'water.outdoor-kitchen',
    name: 'Outdoor kitchen placeholder',
    category: StencilCategory.WATER_OUTDOOR,
    defaultDimensions: feet(8, 3),
    defaultFill: FEATURE_FILL,
    defaultStroke: FEATURE_STROKE,
    measurementBehavior: MeasurementBehavior.FEATURE_COUNT,
    pricingBehavior: PricingBehavior.FEATURE_FIXED,
    exportVisibility: ExportVisibility.BOTH,
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: [EditableProperty.WIDTH, EditableProperty.HEIGHT, EditableProperty.ROTATION, EditableProperty.NOTE],
    shapeKind: ShapeKind.STENCIL,
  },
]

export const STENCILS: Stencil[] = [
  ...poolShapes,
  ...interiorFeatures,
  ...deckHouse,
  ...constructionSymbols,
  ...waterOutdoor,
]

export function stencilsByCategory(): Record<StencilCategory, Stencil[]> {
  return {
    [StencilCategory.POOL_SHAPE]: poolShapes,
    [StencilCategory.INTERIOR_FEATURE]: interiorFeatures,
    [StencilCategory.DECK_HOUSE]: deckHouse,
    [StencilCategory.CONSTRUCTION_SYMBOL]: constructionSymbols,
    [StencilCategory.WATER_OUTDOOR]: waterOutdoor,
  }
}

export function getStencil(id: string): Stencil | undefined {
  return STENCILS.find((s) => s.id === id)
}

export type { Stencil } from './types'
