import type { Stencil } from './types'

const POOL_WATER_FILL = '#5BA8D6'
const POOL_STROKE = '#2C5F84'
const SPA_FILL = '#7BC2DD'
const CONCRETE_FILL = '#D6D2C7'
const PAVER_FILL = '#B69B7C'
const GRASS_FILL = '#7FB069'
const LANAI_FILL = '#E5DCC5'
const SCREEN_FILL = '#9CA3AF'
const COPING_FILL = '#C4B6A0'
const FEATURE_FILL = '#FEE2A8'
const FEATURE_STROKE = '#A87E2A'
const SYMBOL_FILL = '#FFFFFF'
const SYMBOL_STROKE = '#1F2937'
const FIRE_FILL = '#E25822'
const WATER_FEATURE_FILL = '#7FB7D6'

const inches = (width: number, height: number): Stencil['defaultDimensions'] => ({ width, height, unit: 'in' })
const feet = (width: number, height: number): Stencil['defaultDimensions'] => ({ width, height, unit: 'ft' })

// Pool shapes — dimensions in inches (1 ft = 12 in)
const poolShapes: Stencil[] = [
  {
    id: 'pool.rectangle',
    name: 'Standard rectangle',
    category: 'pool-shape',
    defaultDimensions: inches(360, 168),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'pool-area-perimeter-gallons',
    pricingBehavior: 'pool-base',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'depth-shallow', 'depth-deep', 'rotation', 'fill', 'material'],
  },
  {
    id: 'pool.round-corners',
    name: 'Round corners',
    category: 'pool-shape',
    defaultDimensions: inches(360, 168),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'pool-area-perimeter-gallons',
    pricingBehavior: 'pool-base',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'radius', 'depth-shallow', 'depth-deep', 'rotation', 'fill', 'material'],
  },
  {
    id: 'pool.grecian',
    name: 'Grecian',
    category: 'pool-shape',
    defaultDimensions: inches(396, 192),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'pool-area-perimeter-gallons',
    pricingBehavior: 'pool-base',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'depth-shallow', 'depth-deep', 'rotation', 'fill', 'material'],
  },
  {
    id: 'pool.roman',
    name: 'Roman',
    category: 'pool-shape',
    defaultDimensions: inches(396, 192),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'pool-area-perimeter-gallons',
    pricingBehavior: 'pool-base',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'depth-shallow', 'depth-deep', 'rotation', 'fill', 'material'],
  },
  {
    id: 'pool.roman-two-master',
    name: 'Roman two master',
    category: 'pool-shape',
    defaultDimensions: inches(420, 204),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'pool-area-perimeter-gallons',
    pricingBehavior: 'pool-base',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'depth-shallow', 'depth-deep', 'rotation', 'fill', 'material'],
  },
  {
    id: 'pool.roman-two-point-one-master',
    name: 'Roman two point one master',
    category: 'pool-shape',
    defaultDimensions: inches(432, 216),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'pool-area-perimeter-gallons',
    pricingBehavior: 'pool-base',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'depth-shallow', 'depth-deep', 'rotation', 'fill', 'material'],
  },
  {
    id: 'pool.freeform-kidney',
    name: 'Freeform kidney',
    category: 'pool-shape',
    defaultDimensions: inches(432, 240),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'pool-area-perimeter-gallons',
    pricingBehavior: 'pool-base',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'depth-shallow', 'depth-deep', 'rotation', 'fill', 'material'],
  },
  {
    id: 'pool.standard-steps',
    name: 'Standard steps',
    category: 'pool-shape',
    defaultDimensions: inches(96, 36),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-fixed',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'count', 'rotation'],
  },
  {
    id: 'pool.one-step',
    name: 'One step',
    category: 'pool-shape',
    defaultDimensions: inches(96, 12),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-fixed',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation'],
  },
  {
    id: 'pool.step-sets',
    name: 'Step sets',
    category: 'pool-shape',
    defaultDimensions: inches(96, 48),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-fixed',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'count', 'rotation'],
  },
  {
    id: 'pool.corner-steps',
    name: 'Corner steps',
    category: 'pool-shape',
    defaultDimensions: inches(60, 60),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-fixed',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation'],
  },
  {
    id: 'pool.square-steps',
    name: 'Square steps',
    category: 'pool-shape',
    defaultDimensions: inches(72, 72),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-fixed',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation'],
  },
  {
    id: 'pool.spa',
    name: 'Spa',
    category: 'pool-shape',
    defaultDimensions: inches(96, 96),
    defaultFill: SPA_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'spa-area-perimeter-gallons',
    pricingBehavior: 'spa-base',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'depth-shallow', 'rotation', 'fill', 'material'],
  },
  {
    id: 'pool.rectangle-pool-and-spa',
    name: 'Rectangle pool and spa',
    category: 'pool-shape',
    defaultDimensions: inches(456, 192),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'pool-area-perimeter-gallons',
    pricingBehavior: 'pool-base',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'depth-shallow', 'depth-deep', 'rotation', 'fill', 'material'],
  },
  {
    id: 'pool.grecian-pool-and-spa',
    name: 'Grecian pool and spa',
    category: 'pool-shape',
    defaultDimensions: inches(480, 204),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'pool-area-perimeter-gallons',
    pricingBehavior: 'pool-base',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'depth-shallow', 'depth-deep', 'rotation', 'fill', 'material'],
  },
  {
    id: 'pool.roman-pool-and-spa',
    name: 'Roman pool and spa',
    category: 'pool-shape',
    defaultDimensions: inches(480, 204),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'pool-area-perimeter-gallons',
    pricingBehavior: 'pool-base',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'depth-shallow', 'depth-deep', 'rotation', 'fill', 'material'],
  },
  {
    id: 'pool.freeform-pool-and-spa',
    name: 'Freeform pool and spa',
    category: 'pool-shape',
    defaultDimensions: inches(516, 252),
    defaultFill: POOL_WATER_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'pool-area-perimeter-gallons',
    pricingBehavior: 'pool-base',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'depth-shallow', 'depth-deep', 'rotation', 'fill', 'material'],
  },
]

const interiorFeatures: Stencil[] = [
  {
    id: 'feature.swim-out-bench',
    name: 'Swim out bench',
    category: 'interior-feature',
    defaultDimensions: inches(48, 18),
    defaultFill: SPA_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'bench-linear-feet',
    pricingBehavior: 'bench-per-lf',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation'],
  },
  {
    id: 'feature.bench',
    name: 'Bench',
    category: 'interior-feature',
    defaultDimensions: inches(60, 18),
    defaultFill: SPA_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'bench-linear-feet',
    pricingBehavior: 'bench-per-lf',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation'],
  },
  {
    id: 'feature.sun-shelf',
    name: 'Sun shelf',
    category: 'interior-feature',
    defaultDimensions: inches(96, 60),
    defaultFill: SPA_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'shelf-area',
    pricingBehavior: 'feature-fixed',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation'],
  },
  {
    id: 'feature.tanning-ledge',
    name: 'Tanning ledge',
    category: 'interior-feature',
    defaultDimensions: inches(120, 72),
    defaultFill: SPA_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'shelf-area',
    pricingBehavior: 'feature-fixed',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation'],
  },
  {
    id: 'feature.bubblers',
    name: 'Bubblers',
    category: 'interior-feature',
    defaultDimensions: inches(6, 6),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-per-unit',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['count', 'rotation'],
  },
  {
    id: 'feature.umbrella-hole',
    name: 'Umbrella hole',
    category: 'interior-feature',
    defaultDimensions: inches(4, 4),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-per-unit',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['count', 'rotation'],
  },
  {
    id: 'feature.deck-jets',
    name: 'Deck jets',
    category: 'interior-feature',
    defaultDimensions: inches(6, 6),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-per-unit',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['count', 'rotation'],
  },
  {
    id: 'feature.deep-end-marker',
    name: 'Deep end marker',
    category: 'interior-feature',
    defaultDimensions: inches(8, 8),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'point-marker',
    pricingBehavior: 'none',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['label', 'rotation'],
  },
  {
    id: 'feature.shallow-end-marker',
    name: 'Shallow end marker',
    category: 'interior-feature',
    defaultDimensions: inches(8, 8),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'point-marker',
    pricingBehavior: 'none',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['label', 'rotation'],
  },
  {
    id: 'feature.main-drain',
    name: 'Main drain',
    category: 'interior-feature',
    defaultDimensions: inches(8, 8),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-per-unit',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['count', 'rotation'],
  },
  {
    id: 'feature.light',
    name: 'Light',
    category: 'interior-feature',
    defaultDimensions: inches(6, 6),
    defaultFill: '#FFE066',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-per-unit',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['count', 'rotation'],
  },
  {
    id: 'feature.return',
    name: 'Return',
    category: 'interior-feature',
    defaultDimensions: inches(4, 4),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-per-unit',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['count', 'rotation'],
  },
]

const deckHouse: Stencil[] = [
  {
    id: 'deck.concrete',
    name: 'Concrete deck',
    category: 'deck-house',
    defaultDimensions: feet(40, 24),
    defaultFill: CONCRETE_FILL,
    defaultStroke: '#8A8377',
    measurementBehavior: 'deck-area',
    pricingBehavior: 'deck-per-sqft',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation', 'fill', 'material'],
  },
  {
    id: 'deck.paver',
    name: 'Paver deck',
    category: 'deck-house',
    defaultDimensions: feet(40, 24),
    defaultFill: PAVER_FILL,
    defaultStroke: '#7A6650',
    measurementBehavior: 'deck-area',
    pricingBehavior: 'deck-per-sqft',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation', 'fill', 'material'],
  },
  {
    id: 'deck.grass-area',
    name: 'Grass area',
    category: 'deck-house',
    defaultDimensions: feet(20, 20),
    defaultFill: GRASS_FILL,
    defaultStroke: '#4F7340',
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'both',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation', 'fill'],
  },
  {
    id: 'deck.lanai',
    name: 'Lanai',
    category: 'deck-house',
    defaultDimensions: feet(20, 16),
    defaultFill: LANAI_FILL,
    defaultStroke: '#A89D80',
    measurementBehavior: 'lanai-area',
    pricingBehavior: 'lanai-per-sqft',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation', 'fill', 'material'],
  },
  {
    id: 'deck.covered-lanai',
    name: 'Covered lanai',
    category: 'deck-house',
    defaultDimensions: feet(20, 16),
    defaultFill: LANAI_FILL,
    defaultStroke: '#A89D80',
    measurementBehavior: 'lanai-area',
    pricingBehavior: 'lanai-per-sqft',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation', 'fill', 'material'],
  },
  {
    id: 'deck.pillar',
    name: 'Pillar',
    category: 'deck-house',
    defaultDimensions: inches(12, 12),
    defaultFill: '#A8A29E',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-per-unit',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['count', 'rotation'],
  },
  {
    id: 'deck.corner-pillar',
    name: 'Corner pillar',
    category: 'deck-house',
    defaultDimensions: inches(14, 14),
    defaultFill: '#A8A29E',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-per-unit',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['count', 'rotation'],
  },
  {
    id: 'deck.wall',
    name: 'Wall',
    category: 'deck-house',
    defaultDimensions: feet(10, 1),
    defaultFill: '#9CA3AF',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'wall-linear-feet',
    pricingBehavior: 'wall-per-lf',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['length', 'rotation', 'fill', 'material'],
  },
  {
    id: 'deck.raised-deck',
    name: 'Raised deck',
    category: 'deck-house',
    defaultDimensions: feet(16, 12),
    defaultFill: PAVER_FILL,
    defaultStroke: '#7A6650',
    measurementBehavior: 'deck-area',
    pricingBehavior: 'deck-per-sqft',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation', 'fill', 'material'],
  },
  {
    id: 'deck.waterfall-wall',
    name: 'Waterfall wall',
    category: 'deck-house',
    defaultDimensions: feet(8, 1),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'wall-linear-feet',
    pricingBehavior: 'wall-per-lf',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['length', 'rotation', 'fill', 'material'],
  },
  {
    id: 'deck.step-down',
    name: 'Step down',
    category: 'deck-house',
    defaultDimensions: feet(4, 1),
    defaultFill: CONCRETE_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-per-unit',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'rotation'],
  },
  {
    id: 'deck.drain-line',
    name: 'Drain line',
    category: 'deck-house',
    defaultDimensions: feet(20, 1),
    defaultFill: 'transparent',
    defaultStroke: '#1F2937',
    measurementBehavior: 'deco-drain-linear-feet',
    pricingBehavior: 'deco-drain-per-lf',
    exportVisibility: 'construction',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['length', 'rotation'],
  },
  {
    id: 'deck.deco-drain',
    name: 'Deco drain',
    category: 'deck-house',
    defaultDimensions: feet(20, 1),
    defaultFill: 'transparent',
    defaultStroke: '#1F2937',
    measurementBehavior: 'deco-drain-linear-feet',
    pricingBehavior: 'deco-drain-per-lf',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['length', 'rotation'],
  },
  {
    id: 'deck.coping-strip',
    name: 'Coping strip',
    category: 'deck-house',
    defaultDimensions: feet(20, 1),
    defaultFill: COPING_FILL,
    defaultStroke: '#8A7A5A',
    measurementBehavior: 'coping-linear-feet',
    pricingBehavior: 'coping-per-lf',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['length', 'rotation', 'material'],
  },
  {
    id: 'deck.fence',
    name: 'Fence',
    category: 'deck-house',
    defaultDimensions: feet(20, 1),
    defaultFill: '#6B7280',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'fence-linear-feet',
    pricingBehavior: 'fence-per-lf',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['length', 'rotation', 'material'],
  },
  {
    id: 'deck.screen-cage',
    name: 'Screen cage',
    category: 'deck-house',
    defaultDimensions: feet(40, 24),
    defaultFill: SCREEN_FILL,
    defaultStroke: '#4B5563',
    measurementBehavior: 'screen-area',
    pricingBehavior: 'screen-per-sqft',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation', 'material'],
  },
  {
    id: 'deck.access-arrow',
    name: 'Access arrow',
    category: 'deck-house',
    defaultDimensions: inches(48, 12),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['rotation', 'label'],
  },
]

const constructionSymbols: Stencil[] = [
  {
    id: 'symbol.equipment-pad',
    name: 'Equipment pad',
    category: 'construction-symbol',
    defaultDimensions: feet(8, 6),
    defaultFill: CONCRETE_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-fixed',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation', 'note'],
  },
  {
    id: 'symbol.access-arrow',
    name: 'Access arrow',
    category: 'construction-symbol',
    defaultDimensions: inches(48, 12),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['rotation', 'label'],
  },
  {
    id: 'symbol.construction-notes',
    name: 'Construction notes block',
    category: 'construction-symbol',
    defaultDimensions: inches(192, 96),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'note'],
  },
  {
    id: 'symbol.wall-detail',
    name: 'Wall detail',
    category: 'construction-symbol',
    defaultDimensions: inches(96, 96),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'note'],
  },
  {
    id: 'symbol.approval-block',
    name: 'Approval block',
    category: 'construction-symbol',
    defaultDimensions: inches(192, 72),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'both',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'note'],
  },
  {
    id: 'symbol.color-selection-box',
    name: 'Color selection box',
    category: 'construction-symbol',
    defaultDimensions: inches(144, 96),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'both',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'note'],
  },
  {
    id: 'symbol.upgrade-option-box',
    name: 'Upgrade option box',
    category: 'construction-symbol',
    defaultDimensions: inches(144, 96),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'both',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'note'],
  },
  {
    id: 'symbol.gas-line-disclaimer',
    name: 'Gas line disclaimer',
    category: 'construction-symbol',
    defaultDimensions: inches(144, 48),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'note'],
  },
  {
    id: 'symbol.power-line-disclaimer',
    name: 'Power line disclaimer',
    category: 'construction-symbol',
    defaultDimensions: inches(144, 48),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'note'],
  },
  {
    id: 'symbol.job-specification-block',
    name: 'Job specification block',
    category: 'construction-symbol',
    defaultDimensions: inches(192, 96),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'both',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'note'],
  },
  {
    id: 'symbol.total-pricing-block',
    name: 'Total pricing block',
    category: 'construction-symbol',
    defaultDimensions: inches(144, 60),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'customer',
    affectsQuote: false,
    onConstructionSheet: false,
    editableProperties: ['width', 'height', 'note'],
  },
  {
    id: 'symbol.check-mark',
    name: 'Check mark',
    category: 'construction-symbol',
    defaultDimensions: inches(12, 12),
    defaultFill: 'transparent',
    defaultStroke: '#22C55E',
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'both',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['rotation'],
  },
  {
    id: 'symbol.numbered-callout',
    name: 'Numbered callout',
    category: 'construction-symbol',
    defaultDimensions: inches(18, 18),
    defaultFill: SYMBOL_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['label', 'rotation'],
  },
  {
    id: 'symbol.dimension-line',
    name: 'Dimension line',
    category: 'construction-symbol',
    defaultDimensions: feet(10, 1),
    defaultFill: 'transparent',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'dimension-line',
    pricingBehavior: 'none',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['length', 'rotation', 'label'],
  },
  {
    id: 'symbol.center-line',
    name: 'Center line',
    category: 'construction-symbol',
    defaultDimensions: feet(10, 1),
    defaultFill: 'transparent',
    defaultStroke: '#6B7280',
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['length', 'rotation'],
  },
  {
    id: 'symbol.property-line',
    name: 'Property line',
    category: 'construction-symbol',
    defaultDimensions: feet(40, 1),
    defaultFill: 'transparent',
    defaultStroke: '#1F2937',
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['length', 'rotation', 'label'],
  },
  {
    id: 'symbol.setback-line',
    name: 'Setback line',
    category: 'construction-symbol',
    defaultDimensions: feet(20, 1),
    defaultFill: 'transparent',
    defaultStroke: '#9CA3AF',
    measurementBehavior: 'none',
    pricingBehavior: 'none',
    exportVisibility: 'construction',
    affectsQuote: false,
    onConstructionSheet: true,
    editableProperties: ['length', 'rotation', 'label'],
  },
]

const waterOutdoor: Stencil[] = [
  {
    id: 'water.water-bowl',
    name: 'Water bowl',
    category: 'water-outdoor',
    defaultDimensions: inches(24, 24),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-per-unit',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['count', 'rotation'],
  },
  {
    id: 'water.fire-bowl',
    name: 'Fire bowl',
    category: 'water-outdoor',
    defaultDimensions: inches(24, 24),
    defaultFill: FIRE_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-per-unit',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['count', 'rotation'],
  },
  {
    id: 'water.waterfall',
    name: 'Waterfall',
    category: 'water-outdoor',
    defaultDimensions: inches(60, 24),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-fixed',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation'],
  },
  {
    id: 'water.raised-wall',
    name: 'Raised wall',
    category: 'water-outdoor',
    defaultDimensions: feet(8, 1),
    defaultFill: '#A8A29E',
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'wall-linear-feet',
    pricingBehavior: 'wall-per-lf',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['length', 'rotation', 'fill', 'material'],
  },
  {
    id: 'water.spillway',
    name: 'Spillway',
    category: 'water-outdoor',
    defaultDimensions: inches(36, 12),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-fixed',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation'],
  },
  {
    id: 'water.deck-jet',
    name: 'Deck jet',
    category: 'water-outdoor',
    defaultDimensions: inches(6, 6),
    defaultFill: WATER_FEATURE_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-per-unit',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['count', 'rotation'],
  },
  {
    id: 'water.spa-spillover',
    name: 'Spa spillover',
    category: 'water-outdoor',
    defaultDimensions: inches(36, 12),
    defaultFill: SPA_FILL,
    defaultStroke: POOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-fixed',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation'],
  },
  {
    id: 'water.fire-pit',
    name: 'Fire pit',
    category: 'water-outdoor',
    defaultDimensions: inches(48, 48),
    defaultFill: FIRE_FILL,
    defaultStroke: SYMBOL_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-fixed',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation'],
  },
  {
    id: 'water.outdoor-kitchen',
    name: 'Outdoor kitchen placeholder',
    category: 'water-outdoor',
    defaultDimensions: feet(8, 3),
    defaultFill: FEATURE_FILL,
    defaultStroke: FEATURE_STROKE,
    measurementBehavior: 'feature-count',
    pricingBehavior: 'feature-fixed',
    exportVisibility: 'both',
    affectsQuote: true,
    onConstructionSheet: true,
    editableProperties: ['width', 'height', 'rotation', 'note'],
  },
]

export const STENCILS: Stencil[] = [
  ...poolShapes,
  ...interiorFeatures,
  ...deckHouse,
  ...constructionSymbols,
  ...waterOutdoor,
]

export function stencilsByCategory(): Record<Stencil['category'], Stencil[]> {
  return {
    'pool-shape': poolShapes,
    'interior-feature': interiorFeatures,
    'deck-house': deckHouse,
    'construction-symbol': constructionSymbols,
    'water-outdoor': waterOutdoor,
  }
}

export function getStencil(id: string): Stencil | undefined {
  return STENCILS.find((s) => s.id === id)
}

export type { Stencil } from './types'
